<?php

return [

	'Inbox' => [
		'path' => $GLOBALS['OE_SITE_DIR'].'/X12N837/INBOX',
		'pattern' => '*',
		'recursive' => true,
	],

	'Store' => [
		'default' => 'mysql',
		'connections' => [
			'mysql' => [
				'driver'	=> 'mysql',
				'host'		=> $sqlconf['host'],
				'port'		=> $sqlconf['port'],
				'database'	=> $sqlconf['dbase'],
				'username'	=> $sqlconf['login'],
				'password'	=> $sqlconf['pass'],
				'charset'	=> $HTML_CHARSET,
				'collation'	=> 'utf8_unicode_ci',
				'prefix'	=> '',
				'strict'	=> false,
				'engine'	=> null,
			],
		],
		'queryLog' => $GLOBALS['OE_SITE_DIR'].'/X12N837/import.log',
	],

	'Document' => [
		'delimiters' => [
			'data'			=> '*',
			'repetition'	=> '^',
			'component'		=> ':',
			'segment'		=> '~',
		],
	],

	'Aliases' => [
		// Envelope Classes
		'InterchangeControl' => \SunCoastConnection\ClaimsToOEMR\X12N837\Envelope\InterchangeControl::class,
		'FunctionalGroup' => \SunCoastConnection\ClaimsToOEMR\X12N837\Envelope\FunctionalGroup::class,
		'TransactionSet' => \SunCoastConnection\ClaimsToOEMR\X12N837\Envelope\TransactionSet::class,

		// Loop Classes
		'Loop1000' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop1000::class,
		'Loop2000' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2000::class,
		'Loop2010' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2010::class,
		'Loop2300' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2300::class,
		'Loop2305' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2305::class,
		'Loop2310' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2310::class,
		'Loop2320' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2320::class,
		'Loop2330' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2330::class,
		'Loop2400' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2400::class,
		'Loop2410' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2410::class,
		'Loop2420' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2420::class,
		'Loop2430' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2430::class,
		'Loop2440' => \SunCoastConnection\ClaimsToOEMR\X12N837\Loop\Loop2440::class,

		// Segment Classes
		'AMT' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\AMT::class,
		'BHT' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\BHT::class,
		'CAS' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CAS::class,
		'CL1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CL1::class,
		'CLM' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CLM::class,
		'CN1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CN1::class,
		'CR1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR1::class,
		'CR2' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR2::class,
		'CR3' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR3::class,
		'CR4' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR4::class,
		'CR5' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR5::class,
		'CR6' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR6::class,
		'CR7' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR7::class,
		'CR8' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CR8::class,
		'CRC' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CRC::class,
		'CTP' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CTP::class,
		'CUR' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\CUR::class,
		'DMG' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\DMG::class,
		'DN1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\DN1::class,
		'DN2' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\DN2::class,
		'DSB' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\DSB::class,
		'DTP' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\DTP::class,
		'FRM' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\FRM::class,
		'GE' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\GE::class,
		'GS' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\GS::class,
		'HCP' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\HCP::class,
		'HI' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\HI::class,
		'HL' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\HL::class,
		'HSD' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\HSD::class,
		'IEA' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\IEA::class,
		'IMM' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\IMM::class,
		'ISA' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\ISA::class,
		'K3' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\K3::class,
		'LIN' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\LIN::class,
		'LQ' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\LQ::class,
		'LX' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\LX::class,
		'MEA' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\MEA::class,
		'MIA' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\MIA::class,
		'MOA' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\MOA::class,
		'N2' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\N2::class,
		'N3' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\N3::class,
		'N4' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\N4::class,
		'NM1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\NM1::class,
		'NTE' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\NTE::class,
		'OI' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\OI::class,
		'PAT' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\PAT::class,
		'PER' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\PER::class,
		'PRV' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\PRV::class,
		'PS1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\PS1::class,
		'PWK' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\PWK::class,
		'QTY' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\QTY::class,
		'REF' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\REF::class,
		'SBR' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SBR::class,
		'SE' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SE::class,
		'ST' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\ST::class,
		'SV1' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV1::class,
		'SV2' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV2::class,
		'SV3' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV3::class,
		'SV4' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV4::class,
		'SV5' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV5::class,
		'SV6' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV6::class,
		'SV7' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SV7::class,
		'SVD' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\SVD::class,
		'TOO' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\TOO::class,
		'UR' => \SunCoastConnection\ClaimsToOEMR\X12N837\Segment\UR::class,

		// Models Classes
		'address' => \SunCoastConnection\ClaimsToOEMR\Models\Addresses::class,
		'billing' => \SunCoastConnection\ClaimsToOEMR\Models\Billing::class,
		'facility' => \SunCoastConnection\ClaimsToOEMR\Models\Facilities::class,
		'formEncounter' => \SunCoastConnection\ClaimsToOEMR\Models\FormEncounters::class,
		'form' => \SunCoastConnection\ClaimsToOEMR\Models\Forms::class,
		'group' => \SunCoastConnection\ClaimsToOEMR\Models\Groups::class,
		'insuranceCompany' => \SunCoastConnection\ClaimsToOEMR\Models\InsuranceCompanies::class,
		'insuranceData' => \SunCoastConnection\ClaimsToOEMR\Models\InsuranceData::class,
		'patientData' => \SunCoastConnection\ClaimsToOEMR\Models\PatientData::class,
		'phoneNumber' => \SunCoastConnection\ClaimsToOEMR\Models\PhoneNumbers::class,
		'user' => \SunCoastConnection\ClaimsToOEMR\Models\Users::class,
		'x12Partners' => \SunCoastConnection\ClaimsToOEMR\Models\X12Partners::class,
	],

];