TRUNCATE TABLE `layout_options`;
INSERT INTO `layout_options` (`form_id`, `field_id`, `group_name`, `title`, `seq`, `data_type`, `uor`, `fld_length`, `max_length`, `list_id`, `titlecols`, `datacols`, `default_value`, `edit_options`, `description`, `fld_rows`, `list_backup_id`, `source`, `conditions`) VALUES
('DEM', 'title', '1Facesheet', 'Name', 1, 1, 0, 0, 0, 'titles', 1, 1, '', 'N', 'Title', 0, '', 'F', ''),
('DEM', 'fname', '1Facesheet', 'Name', 2, 2, 2, 10, 63, '', 1, 3, '', 'CD', 'First Name', 0, '', 'F', ''),
('DEM', 'mname', '1Facesheet', '', 3, 2, 1, 2, 63, '', 0, 0, '', 'C', 'Middle Name', 0, '', 'F', ''),
('DEM', 'lname', '1Facesheet', '', 4, 2, 2, 10, 63, '', 0, 0, '', 'CD', 'Last Name', 0, '', 'F', ''),
('DEM', 'pubpid', '1Facesheet', 'Patient ID', 5, 2, 0, 10, 15, '', 1, 1, '', 'ND', 'External identifier', 0, '', 'F', ''),
('DEM', 'DOB', '1Facesheet', 'DOB', 6, 4, 2, 0, 10, '', 1, 1, '', 'D', 'Date of Birth', 0, '', 'F', ''),
('DEM', 'sex', '1Facesheet', 'Sex', 7, 1, 2, 0, 0, 'sex', 1, 1, '', 'N', 'Sex', 0, '', 'F', ''),
('DEM', 'ss', '1Facesheet', 'S.S.', 10, 2, 0, 11, 11, '', 1, 1, '', '', 'Social Security Number', 0, '', 'F', ''),
('DEM', 'drivers_license', '1Facesheet', 'License/ID', 9, 2, 0, 15, 63, '', 1, 1, '', '', 'Drivers License or State ID', 0, '', 'F', ''),
('DEM', 'status', '1Facesheet', 'Marital Status', 10, 1, 0, 0, 0, 'marital', 1, 3, '', '', 'Marital Status', 0, '', 'F', ''),
('DEM', 'genericname1', '1Facesheet', 'User Defined', 11, 2, 0, 15, 63, '', 1, 3, '', '', 'User Defined Field', 0, '', 'F', ''),
('DEM', 'genericval1', '1Facesheet', '', 12, 2, 0, 15, 63, '', 0, 0, '', '', 'User Defined Field', 0, '', 'F', ''),
('DEM', 'genericname2', '1Facesheet', '', 13, 2, 0, 15, 63, '', 0, 0, '', '', 'User Defined Field', 0, '', 'F', ''),
('DEM', 'genericval2', '1Facesheet', '', 14, 2, 0, 15, 63, '', 0, 0, '', '', 'User Defined Field', 0, '', 'F', ''),
('DEM', 'squad', '1Facesheet', 'Squad', 15, 13, 0, 0, 0, '', 1, 3, '', '', 'Squad Membership', 0, '', 'F', ''),
('DEM', 'pricelevel', '1Facesheet', 'Price Level', 16, 1, 0, 0, 0, 'pricelevel', 1, 1, '', '', 'Discount Level', 0, '', 'F', ''),
('DEM', 'street', '2Contact', 'Address', 1, 2, 1, 25, 63, '', 1, 1, '', 'C', 'Street and Number', 0, '', 'F', ''),
('DEM', 'city', '2Contact', 'City', 2, 2, 1, 15, 63, '', 1, 1, '', 'C', 'City Name', 0, '', 'F', ''),
('DEM', 'state', '2Contact', 'State', 3, 26, 1, 0, 0, 'state', 1, 1, '', '', 'State/Locality', 0, '', 'F', ''),
('DEM', 'postal_code', '2Contact', 'Postal Code', 4, 2, 1, 6, 63, '', 1, 1, '', '', 'Postal Code', 0, '', 'F', ''),
('DEM', 'country_code', '2Contact', 'Country', 5, 26, 1, 0, 0, 'country', 1, 1, '', '', 'Country', 0, '', 'F', ''),
('DEM', 'county', '2Contact', 'County', 5, 26, 0, 0, 0, 'county', 1, 1, '', '', 'County', 0, '', 'F', ''),
('DEM', 'mothersname', '2Contact', 'Mother\'s Name', 6, 2, 0, 20, 63, '', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'guardiansname', '2Contact', 'Guardian\'s Name', 7, 2, 0, 20, 63, '', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'contact_relationship', '2Contact', 'Emergency Contact', 8, 2, 0, 10, 63, '', 1, 1, '', 'C', 'Emergency Contact Person', 0, '', 'F', ''),
('DEM', 'phone_contact', '2Contact', 'Emergency Phone', 9, 2, 0, 20, 63, '', 1, 1, '', 'P', 'Emergency Contact Phone Number', 0, '', 'F', ''),
('DEM', 'phone_home', '2Contact', 'Home Phone', 10, 2, 0, 20, 63, '', 1, 1, '', 'P', 'Home Phone Number', 0, '', 'F', ''),
('DEM', 'phone_biz', '2Contact', 'Work Phone', 11, 2, 0, 20, 63, '', 1, 1, '', 'P', 'Work Phone Number', 0, '', 'F', ''),
('DEM', 'phone_cell', '2Contact', 'Mobile Phone', 12, 2, 0, 20, 63, '', 1, 1, '', 'P', 'Cell Phone Number', 0, '', 'F', ''),
('DEM', 'email', '2Contact', 'Contact Email', 13, 2, 0, 30, 95, '', 1, 1, '', '', 'Contact Email Address', 0, '', 'F', ''),
('DEM', 'email_direct', '2Contact', 'Trusted Email', 14, 2, 0, 30, 95, '', 1, 1, '', '', 'Trusted Direct Email Address', 0, '', 'F', ''),
('DEM', 'providerID', '1Facesheet', 'Provider', 8, 11, 1, 0, 0, '', 1, 3, '', '', 'Provider', 0, '', 'F', ''),
('DEM', 'ref_providerID', '1Facesheet', 'Referring Provider', 9, 11, 1, 0, 0, '', 1, 3, '', '', 'Referring Provider', 0, '', 'F', ''),
('DEM', 'pharmacy_id', '3Choices', 'Pharmacy', 3, 12, 0, 0, 0, '', 1, 3, '', '', 'Preferred Pharmacy', 0, '', 'F', ''),
('DEM', 'hipaa_notice', '3Choices', 'HIPAA Notice Received', 4, 1, 0, 0, 0, 'yesno', 1, 1, '', '', 'Did you receive a copy of the HIPAA Notice?', 0, '', 'F', ''),
('DEM', 'hipaa_voice', '3Choices', 'Allow Voice Message', 5, 1, 0, 0, 0, 'yesno', 1, 1, '', '', 'Allow telephone messages?', 0, '', 'F', ''),
('DEM', 'hipaa_message', '3Choices', 'Leave Message With', 6, 2, 0, 20, 63, '', 1, 1, '', '', 'With whom may we leave a message?', 0, '', 'F', ''),
('DEM', 'hipaa_mail', '3Choices', 'Allow Mail Message', 7, 1, 0, 0, 0, 'yesno', 1, 1, '', '', 'Allow email messages?', 0, '', 'F', ''),
('DEM', 'hipaa_allowsms', '3Choices', 'Allow SMS', 8, 1, 0, 0, 0, 'yesno', 1, 1, '', '', 'Allow SMS (text messages)?', 0, '', 'F', ''),
('DEM', 'hipaa_allowemail', '3Choices', 'Allow Email', 9, 1, 0, 0, 0, 'yesno', 1, 1, '', '', 'Allow Email?', 0, '', 'F', ''),
('DEM', 'allow_imm_reg_use', '3Choices', 'Allow Immunization Registry Use', 10, 1, 0, 0, 0, 'yesno', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'allow_imm_info_share', '3Choices', 'Allow Immunization Info Sharing', 11, 1, 0, 0, 0, 'yesno', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'allow_health_info_ex', '3Choices', 'Allow Health Information Exchange', 12, 1, 0, 0, 0, 'yesno', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'allow_patient_portal', '3Choices', 'Allow Patient Portal', 13, 1, 0, 0, 0, 'yesno', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'care_team', '3Choices', 'Care Team', 14, 11, 0, 0, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('DEM', 'cmsportal_login', '3Choices', 'CMS Portal Login', 15, 2, 0, 30, 60, '', 1, 1, '', '', 'CMS Portal Login ID', 0, '', 'F', ''),
('DEM', 'occupation', '4Employer', 'Occupation', 1, 26, 0, 0, 0, 'Occupation', 1, 1, '', '', 'Occupation', 0, '', 'F', ''),
('DEM', 'industry', '4Employer', 'Industry', 1, 26, 0, 0, 0, 'Industry', 1, 1, '', '', 'Industry', 0, '', 'F', ''),
('DEM', 'em_name', '4Employer', 'Employer Name', 2, 2, 0, 20, 63, '', 1, 1, '', 'C', 'Employer Name', 0, '', 'F', ''),
('DEM', 'em_street', '4Employer', 'Employer Address', 3, 2, 0, 25, 63, '', 1, 1, '', 'C', 'Street and Number', 0, '', 'F', ''),
('DEM', 'em_city', '4Employer', 'City', 4, 2, 0, 15, 63, '', 1, 1, '', 'C', 'City Name', 0, '', 'F', ''),
('DEM', 'em_state', '4Employer', 'State', 5, 26, 0, 0, 0, 'state', 1, 1, '', '', 'State/Locality', 0, '', 'F', ''),
('DEM', 'em_postal_code', '4Employer', 'Postal Code', 6, 2, 0, 6, 63, '', 1, 1, '', '', 'Postal Code', 0, '', 'F', ''),
('DEM', 'em_country', '4Employer', 'Country', 7, 26, 0, 0, 0, 'country', 1, 1, '', '', 'Country', 0, '', 'F', ''),
('DEM', 'language', '5Stats', 'Language', 1, 1, 0, 0, 0, 'language', 1, 3, '', '', 'Preferred Language', 0, '', 'F', ''),
('DEM', 'ethnicity', '5Stats', 'Ethnicity', 2, 33, 0, 0, 0, 'ethnicity', 1, 1, '', '', 'Ethnicity', 0, 'ethrace', 'F', ''),
('DEM', 'race', '5Stats', 'Race', 3, 36, 1, 0, 0, 'race', 1, 1, '', '', 'Race', 0, 'ethrace', 'F', ''),
('DEM', 'financial_review', '5Stats', 'Financial Review Date', 4, 2, 0, 10, 20, '', 1, 1, '', 'D', 'Financial Review Date', 0, '', 'F', ''),
('DEM', 'family_size', '5Stats', 'Family Size', 4, 2, 0, 20, 63, '', 1, 1, '', '', 'Family Size', 0, '', 'F', ''),
('DEM', 'monthly_income', '5Stats', 'Monthly Income', 5, 2, 0, 20, 63, '', 1, 1, '', '', 'Monthly Income', 0, '', 'F', ''),
('DEM', 'homeless', '5Stats', 'Homeless, etc.', 6, 2, 0, 20, 63, '', 1, 1, '', '', 'Homeless or similar?', 0, '', 'F', ''),
('DEM', 'interpretter', '5Stats', 'Interpreter', 7, 2, 0, 20, 63, '', 1, 1, '', '', 'Interpreter needed?', 0, '', 'F', ''),
('DEM', 'migrantseasonal', '5Stats', 'Migrant/Seasonal', 8, 2, 0, 20, 63, '', 1, 1, '', '', 'Migrant or seasonal worker?', 0, '', 'F', ''),
('DEM', 'contrastart', '5Stats', 'Contraceptives Start', 9, 4, 0, 0, 10, '', 1, 1, '', '', 'Date contraceptive services initially provided', 0, '', 'F', ''),
('DEM', 'referral_source', '5Stats', 'Referral Source', 10, 26, 0, 0, 0, 'refsource', 1, 1, '', '', 'How did they hear about us', 0, '', 'F', ''),
('DEM', 'vfc', '5Stats', 'VFC', 12, 1, 0, 0, 0, 'eligibility', 1, 1, '', '', 'Eligibility status for Vaccine for Children supplied vaccine', 0, '', 'F', ''),
('DEM', 'religion', '5Stats', 'Religion', 13, 1, 0, 0, 0, 'religious_affiliation', 1, 3, '', '', 'Patient Religion', 0, '', 'F', ''),
('DEM', 'deceased_date', '6Misc', 'Date Deceased', 1, 4, 1, 0, 20, '', 1, 3, '', 'D', 'If person is deceased, then enter date of death.', 0, '', 'F', ''),
('DEM', 'deceased_reason', '6Misc', 'Reason Deceased', 2, 2, 1, 30, 255, '', 1, 3, '', '', 'Reason for Death', 0, '', 'F', ''),
('DEM', 'usertext1', '6Misc', 'User Defined Text 1', 3, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext2', '6Misc', 'User Defined Text 2', 4, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext3', '6Misc', 'User Defined Text 3', 5, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext4', '6Misc', 'User Defined Text 4', 6, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext5', '6Misc', 'User Defined Text 5', 7, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext6', '6Misc', 'User Defined Text 6', 8, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext7', '6Misc', 'User Defined Text 7', 9, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'usertext8', '6Misc', 'User Defined Text 8', 10, 2, 0, 10, 63, '', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist1', '6Misc', 'User Defined List 1', 11, 1, 0, 0, 0, 'userlist1', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist2', '6Misc', 'User DefinedList 2', 12, 1, 0, 0, 0, 'userlist2', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist3', '6Misc', 'User Defined List 3', 13, 1, 0, 0, 0, 'userlist3', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist4', '6Misc', 'User Defined List 4', 14, 1, 0, 0, 0, 'userlist4', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist5', '6Misc', 'User Defined List 5', 15, 1, 0, 0, 0, 'userlist5', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist6', '6Misc', 'User Defined List 6', 16, 1, 0, 0, 0, 'userlist6', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'userlist7', '6Misc', 'User Defined List 7', 17, 1, 0, 0, 0, 'userlist7', 1, 1, '', '', 'User Defined', 0, '', 'F', ''),
('DEM', 'regdate', '6Misc', 'Registration Date', 18, 4, 0, 0, 10, '', 1, 1, '', 'D', 'Start Date at This Clinic', 0, '', 'F', ''),
('LBTref', 'refer_date', '1Referral', 'Referral Date', 1, 4, 2, 0, 0, '', 1, 1, 'C', 'D', 'Date of referral', 0, '', 'F', ''),
('LBTref', 'refer_from', '1Referral', 'Refer By', 2, 10, 2, 0, 0, '', 1, 1, '', '', 'Referral By', 0, '', 'F', ''),
('LBTref', 'refer_external', '1Referral', 'External Referral', 3, 1, 1, 0, 0, 'boolean', 1, 1, '', '', 'External referral?', 0, '', 'F', ''),
('LBTref', 'refer_to', '1Referral', 'Refer To', 4, 14, 2, 0, 0, '', 1, 1, '', '', 'Referral To', 0, '', 'F', ''),
('LBTref', 'body', '1Referral', 'Reason', 5, 3, 2, 30, 0, '', 1, 1, '', '', 'Reason for referral', 3, '', 'F', ''),
('LBTref', 'refer_diag', '1Referral', 'Referrer Diagnosis', 6, 2, 1, 30, 255, '', 1, 1, '', 'X', 'Referrer diagnosis', 0, '', 'F', ''),
('LBTref', 'refer_risk_level', '1Referral', 'Risk Level', 7, 1, 1, 0, 0, 'risklevel', 1, 1, '', '', 'Level of urgency', 0, '', 'F', ''),
('LBTref', 'refer_vitals', '1Referral', 'Include Vitals', 8, 1, 1, 0, 0, 'boolean', 1, 1, '', '', 'Include vitals data?', 0, '', 'F', ''),
('LBTref', 'refer_related_code', '1Referral', 'Requested Service', 9, 15, 1, 30, 255, '', 1, 1, '', '', 'Billing Code for Requested Service', 0, '', 'F', ''),
('LBTref', 'reply_date', '2Counter-Referral', 'Reply Date', 10, 4, 1, 0, 0, '', 1, 1, '', 'D', 'Date of reply', 0, '', 'F', ''),
('LBTref', 'reply_from', '2Counter-Referral', 'Reply From', 11, 2, 1, 30, 255, '', 1, 1, '', '', 'Who replied?', 0, '', 'F', ''),
('LBTref', 'reply_init_diag', '2Counter-Referral', 'Presumed Diagnosis', 12, 2, 1, 30, 255, '', 1, 1, '', '', 'Presumed diagnosis by specialist', 0, '', 'F', ''),
('LBTref', 'reply_final_diag', '2Counter-Referral', 'Final Diagnosis', 13, 2, 1, 30, 255, '', 1, 1, '', '', 'Final diagnosis by specialist', 0, '', 'F', ''),
('LBTref', 'reply_documents', '2Counter-Referral', 'Documents', 14, 2, 1, 30, 255, '', 1, 1, '', '', 'Where may related scanned or paper documents be found?', 0, '', 'F', ''),
('LBTref', 'reply_findings', '2Counter-Referral', 'Findings', 15, 3, 1, 30, 0, '', 1, 1, '', '', 'Findings by specialist', 3, '', 'F', ''),
('LBTref', 'reply_services', '2Counter-Referral', 'Services Provided', 16, 3, 1, 30, 0, '', 1, 1, '', '', 'Service provided by specialist', 3, '', 'F', ''),
('LBTref', 'reply_recommend', '2Counter-Referral', 'Recommendations', 17, 3, 1, 30, 0, '', 1, 1, '', '', 'Recommendations by specialist', 3, '', 'F', ''),
('LBTref', 'reply_rx_refer', '2Counter-Referral', 'Prescriptions/Referrals', 18, 3, 1, 30, 0, '', 1, 1, '', '', 'Prescriptions and/or referrals by specialist', 3, '', 'F', ''),
('LBTptreq', 'body', '1', 'Details', 10, 3, 2, 30, 0, '', 1, 3, '', '', 'Content', 5, '', 'F', ''),
('LBTphreq', 'body', '1', 'Details', 10, 3, 2, 30, 0, '', 1, 3, '', '', 'Content', 5, '', 'F', ''),
('LBTlegal', 'body', '1', 'Details', 10, 3, 2, 30, 0, '', 1, 3, '', '', 'Content', 5, '', 'F', ''),
('LBTbill', 'body', '1', 'Details', 10, 3, 2, 30, 0, '', 1, 3, '', '', 'Content', 5, '', 'F', ''),
('HIS', 'usertext11', '1General', 'Risk Factors', 1, 21, 1, 0, 0, 'riskfactors', 1, 1, '', '', 'Risk Factors', 0, '', 'F', ''),
('HIS', 'exams', '1General', 'Exams/Tests', 2, 23, 1, 0, 0, 'exams', 1, 1, '', '', 'Exam and test results', 0, '', 'F', ''),
('HIS', 'history_father', '2Family History', 'Father', 1, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'dc_father', '2Family History', 'Diagnosis Code', 2, 15, 1, 0, 255, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'history_mother', '2Family History', 'Mother', 3, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'dc_mother', '2Family History', 'Diagnosis Code', 4, 15, 1, 0, 255, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'history_siblings', '2Family History', 'Siblings', 5, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'dc_siblings', '2Family History', 'Diagnosis Code', 6, 15, 1, 0, 255, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'history_spouse', '2Family History', 'Spouse', 7, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'dc_spouse', '2Family History', 'Diagnosis Code', 8, 15, 1, 0, 255, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'history_offspring', '2Family History', 'Offspring', 9, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'dc_offspring', '2Family History', 'Diagnosis Code', 10, 15, 1, 0, 255, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_cancer', '3Relatives', 'Cancer', 1, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_tuberculosis', '3Relatives', 'Tuberculosis', 2, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_diabetes', '3Relatives', 'Diabetes', 3, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_high_blood_pressure', '3Relatives', 'High Blood Pressure', 4, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_heart_problems', '3Relatives', 'Heart Problems', 5, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_stroke', '3Relatives', 'Stroke', 6, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_epilepsy', '3Relatives', 'Epilepsy', 7, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_mental_illness', '3Relatives', 'Mental Illness', 8, 2, 1, 20, 0, '', 1, 1, '', '', '', 0, '', 'F', ''),
('HIS', 'relatives_suicide', '3Relatives', 'Suicide', 9, 2, 1, 20, 0, '', 1, 3, '', '', '', 0, '', 'F', ''),
('HIS', 'coffee', '4Lifestyle', 'Coffee', 2, 28, 1, 20, 0, '', 1, 3, '', '', 'Caffeine consumption', 0, '', 'F', ''),
('HIS', 'tobacco', '4Lifestyle', 'Tobacco', 1, 32, 1, 0, 0, 'smoking_status', 1, 3, '', '', 'Tobacco use', 0, '', 'F', ''),
('HIS', 'alcohol', '4Lifestyle', 'Alcohol', 3, 28, 1, 20, 0, '', 1, 3, '', '', 'Alcohol consumption', 0, '', 'F', ''),
('HIS', 'recreational_drugs', '4Lifestyle', 'Recreational Drugs', 4, 28, 1, 20, 0, '', 1, 3, '', '', 'Recreational drug use', 0, '', 'F', ''),
('HIS', 'counseling', '4Lifestyle', 'Counseling', 5, 28, 1, 20, 0, '', 1, 3, '', '', 'Counseling activities', 0, '', 'F', ''),
('HIS', 'exercise_patterns', '4Lifestyle', 'Exercise Patterns', 6, 28, 1, 20, 0, '', 1, 3, '', '', 'Exercise patterns', 0, '', 'F', ''),
('HIS', 'hazardous_activities', '4Lifestyle', 'Hazardous Activities', 7, 28, 1, 20, 0, '', 1, 3, '', '', 'Hazardous activities', 0, '', 'F', ''),
('HIS', 'sleep_patterns', '4Lifestyle', 'Sleep Patterns', 8, 2, 1, 20, 0, '', 1, 3, '', '', 'Sleep patterns', 0, '', 'F', ''),
('HIS', 'seatbelt_use', '4Lifestyle', 'Seatbelt Use', 9, 2, 1, 20, 0, '', 1, 3, '', '', 'Seatbelt use', 0, '', 'F', ''),
('HIS', 'name_1', '5Other', 'Name/Value', 1, 2, 1, 10, 255, '', 1, 1, '', '', 'Name 1', 0, '', 'F', ''),
('HIS', 'value_1', '5Other', '', 2, 2, 1, 10, 255, '', 0, 0, '', '', 'Value 1', 0, '', 'F', ''),
('HIS', 'name_2', '5Other', 'Name/Value', 3, 2, 1, 10, 255, '', 1, 1, '', '', 'Name 2', 0, '', 'F', ''),
('HIS', 'value_2', '5Other', '', 4, 2, 1, 10, 255, '', 0, 0, '', '', 'Value 2', 0, '', 'F', ''),
('HIS', 'additional_history', '5Other', 'Additional History', 5, 3, 1, 30, 0, '', 1, 3, '', '', 'Additional history notes', 3, '', 'F', ''),
('HIS', 'userarea11', '5Other', 'User Defined Area 11', 6, 3, 0, 30, 0, '', 1, 3, '', '', 'User Defined', 3, '', 'F', ''),
('HIS', 'userarea12', '5Other', 'User Defined Area 12', 7, 3, 0, 30, 0, '', 1, 3, '', '', 'User Defined', 3, '', 'F', ''),
('FACUSR', 'provider_id', '1General', 'Provider ID', 1, 2, 1, 15, 63, '', 1, 1, '', '', 'Provider ID at Specified Facility', 0, '', 'F', '');
